!"
EventFight2
IsPvp
=22
IsPvp
=2
IsWin
="
EventFight_"
EventFight2
Score	
[]dÈ2
IsWin
=2
	RoomLevel
>2
RoomType
=6*Delta:
PropertyTotalPay"EventPlayerProperty:"EventPlayerProperty*Delta:
PropertyOnlineMinute5"EventPlayerProperty*Delta:
PropertyLevel"
EventFight